test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,8 +13,21 @@ jobs:
           username: ${{ secrets.REMOTE_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           port: ${{ secrets.PORT }}
-          script_stop: true
-          script: docker service update deployment_deployment --image=ivanduka/deployment:fail
+          script: |
+            docker service update deployment_deployment --image=ivanduka/deployment:200 > output
+            cat ./output
+            cat ./output | grep -i roll -q # only need status 0 or 1
+            export rollback=$?
+            echo # for extra line
+            docker service ps deployment_deployment
+            echo # for extra line
+            if [ $rollback = 1 ];
+             then
+               echo "SUCCESS! (no rollback)"
+             else
+               echo "FAIL! (rollback observed)"
+               exit 1
+            fi
 
 #      - name: Set Variables
 #        run: |
