test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,18 +15,21 @@ jobs:
           port: ${{ secrets.PORT }}
           script_stop: true
           script: |
-            whoami
-            echo "$SHELL"
-            docker service update deployment_deployment --image=ivanduka/deployment:201 | grep -i roll
+            docker service update deployment_deployment --image=ivanduka/deployment:201 > output
+            cat ./output
+            cat ./output | grep -i roll -q
             export rollback=$?
+            echo # for extra line
             docker service ps deployment_deployment
+            echo # for extra line
             if [ $rollback = 1 ];
-              then
-                echo "SUCCESS! (no rollback)"
-              else
-                echo "FAIL! (rollback observed)"
-                exit 1
+             then
+               echo "SUCCESS! (no rollback)"
+             else
+               echo "FAIL! (rollback observed)"
+               exit 1
             fi
+
 
 #      - name: Set Variables
 #        run: |
